-- Primary Key Creation Commands 

ALTER TABLE "IMT_DB"."PUBLIC"."COUNTY_NAME" ADD PRIMARY KEY ("County_ID");

ALTER TABLE "IMT_DB"."PUBLIC"."COVID_COUNTYCASES" ADD PRIMARY KEY ("CountyCases_ID");

ALTER TABLE "IMT_DB"."PUBLIC"."COVID_COUNTYDEATHS" ADD PRIMARY KEY ("CountyDeaths_ID");

ALTER TABLE "IMT_DB"."PUBLIC"."COVID_COUNTYHOSPITALIZATIONS" ADD PRIMARY KEY ("CountyHospitalizations_ID");

ALTER TABLE "IMT_DB"."PUBLIC"."COVID_COUNTYVACCINATIONS" ADD PRIMARY KEY ("CountyVaccinations_ID");

ALTER TABLE "IMT_DB"."PUBLIC"."COVID_ZIPCASES" ADD PRIMARY KEY ("ZIPCases_ID");

ALTER TABLE "IMT_DB"."PUBLIC"."COVID_ZIPDEATHS" ADD PRIMARY KEY ("ZIPDeaths_ID");

ALTER TABLE "IMT_DB"."PUBLIC"."COVID_ZIPHOSPITALIZATIONS" ADD PRIMARY KEY ("ZIPHospitalizations_ID");

ALTER TABLE "IMT_DB"."PUBLIC"."STATE_NAME" ADD PRIMARY KEY ("State_ID");

ALTER TABLE "IMT_DB"."PUBLIC"."VACCINATION_SITES" ADD PRIMARY KEY ("Site_ID");

ALTER TABLE "IMT_DB"."PUBLIC"."ZIP_TABLE" ADD PRIMARY KEY ("ZIP_ID");

-- Foreign Key Creation Commands 

ALTER TABLE "IMT_DB"."PUBLIC"."COUNTY_NAME" ADD FOREIGN KEY ("State_ID") 
REFERENCES "IMT_DB"."PUBLIC"."STATE_NAME" ("State_ID");

ALTER TABLE "IMT_DB"."PUBLIC"."ZIP_TABLE" ADD FOREIGN KEY ("County_ID") 
REFERENCES "IMT_DB"."PUBLIC"."COUNTY_NAME" ("County_ID");

ALTER TABLE "IMT_DB"."PUBLIC"."COVID_COUNTYCASES" ADD FOREIGN KEY ("County_ID") 
REFERENCES "IMT_DB"."PUBLIC"."COUNTY_NAME" ("County_ID");

ALTER TABLE "IMT_DB"."PUBLIC"."COVID_COUNTYDEATHS" ADD FOREIGN KEY ("County_ID") 
REFERENCES "IMT_DB"."PUBLIC"."COUNTY_NAME" ("County_ID");

ALTER TABLE "IMT_DB"."PUBLIC"."COVID_COUNTYHOSPITALIZATIONS" ADD FOREIGN KEY ("County_ID") 
REFERENCES "IMT_DB"."PUBLIC"."COUNTY_NAME" ("County_ID");

ALTER TABLE "IMT_DB"."PUBLIC"."COVID_COUNTYVACCINATIONS" ADD FOREIGN KEY ("County_ID") 
REFERENCES "IMT_DB"."PUBLIC"."COUNTY_NAME" ("County_ID");

ALTER TABLE "IMT_DB"."PUBLIC"."COVID_ZIPCASES" ADD FOREIGN KEY ("ZIP_ID") 
REFERENCES "IMT_DB"."PUBLIC"."ZIP_TABLE" ("ZIP_ID");

ALTER TABLE "IMT_DB"."PUBLIC"."COVID_ZIPDEATHS" ADD FOREIGN KEY ("ZIP_ID") 
REFERENCES "IMT_DB"."PUBLIC"."ZIP_TABLE" ("ZIP_ID");

ALTER TABLE "IMT_DB"."PUBLIC"."COVID_ZIPHOSPITALIZATIONS" ADD FOREIGN KEY ("ZIP_ID") 
REFERENCES "IMT_DB"."PUBLIC"."ZIP_TABLE" ("ZIP_ID");

ALTER TABLE "IMT_DB"."PUBLIC"."VACCINATION_SITES" ADD FOREIGN KEY ("ZIP_ID") 
REFERENCES "IMT_DB"."PUBLIC"."ZIP_TABLE" ("ZIP_ID");

ALTER TABLE "IMT_DB"."PUBLIC"."VACCINATION_SITES" ADD FOREIGN KEY ("County_ID") 
REFERENCES "IMT_DB"."PUBLIC"."COUNTY_NAME" ("County_ID");